services:
  web:
    build:
      context: ./django
      args:
        - VOLUME:${DJANGO_WORKDIR}
        - LAUNCH:${DJANGO_LAUNCH_REPO}
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000 
    ports:
      - "8000:8000"
    volumes:
      - ../../API:${DJANGO_WORKDIR}
    environment:
      - POSTGRES_USER=${SQL_USER:-default_us}
      - POSTGRES_PASSWORD=${SQL_PASSWORD:-default_ps}
      - POSTGRES_DB=${SQL_DATABASE:-default_db}
    env_file:
      - .env
    depends_on:
      db:
        condition: "service_healthy"
    restart: always

  db:
    container_name: postgreSQL
    build:
      context: ./postgresql
      args:
        - POSTGRES_USER=${SQL_USER:-default_us}
        - POSTGRES_PASSWORD=${SQL_PASSWORD:-default_ps}
        - POSTGRES_DB=${SQL_DATABASE:-default_db}
    volumes:
      - /home/eslamber/data:${PSQL_DATA_REPO}
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $USER"]
      start_period: 5s
      retries: 10
      interval: 15s
      timeout: 10s
    restart: on-failure
