services:
  web:
    build:
      context: ./django
      args:
        - VOLUME=${DJANGO_WORKDIR:-/home/API}
        - LAUNCH=${DJANGO_LAUNCH_REPO:-/run/launch}
    container_name: django_API
    command: python manage.py runserver 0.0.0.0:8000 
    ports:
      - "8000:8000"
    volumes:
      - ../../API:${DJANGO_WORKDIR:-/home/API}
    environment:
      - POSTGRES_USER=${SQL_USER:-default_us}
      - POSTGRES_PASSWORD=${SQL_PASSWORD:-default_ps}
      - POSTGRES_DB=${SQL_DATABASE:-default_db}
    env_file:
      - .env
    depends_on:
      db:
        condition: "service_healthy"
    networks:
      - backend
      - frontend
    restart: always

  db:
    container_name: postgreSQL_API
    build:
      context: ./postgresql
      args:
        - POSTGRES_USER=${SQL_USER:-default_us}
        - POSTGRES_PASSWORD=${SQL_PASSWORD:-default_ps}
        - POSTGRES_DB=${SQL_DATABASE:-default_db}
    volumes:
      # - /home/tdutel/data/API:${PSQL_DATA_REPO}
      # - /sgoinfre/tdutel/data/API:${PSQL_DATA_REPO}
      - API_v:${PSQL_DATA_REPO}
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $SQL_USER -d $SQL_DATABASE"]
      start_period: 5s
      retries: 10
      interval: 15s
      timeout: 10s
    restart: on-failure

networks:
  backend:
    external: true
  frontend:
    external: true

volumes:
  API_v:
    driver: local
