services:
  web:
    build:
      context: ./django
      args:
        - VOLUME=${DJANGO_WORKDIR:-/home/Pong_back}
        - LAUNCH=${DJANGO_LAUNCH_REPO:-/run/launch}
    container_name: django_pong
    command: python manage.py runserver 0.0.0.0:8000 
    ports:
      - "8002:8000"
    volumes:
      - ../../Pong_project:${DJANGO_WORKDIR:-/home/Pong_back}
    environment:
      - POSTGRES_USER=${SQL_USER:-default_us}
      - POSTGRES_PASSWORD=${SQL_PASSWORD:-default_ps}
      - POSTGRES_DB=${SQL_DATABASE:-default_db}
    env_file:
      - .env
    depends_on:
      db:
        condition: "service_healthy"
    networks:
      - backend
      - Pong_back_db
    restart: always

  db:
    container_name: postgreSQL_Pong
    build:
      context: ./postgresql
      args:
        - POSTGRES_USER=${SQL_USER:-default_us}
        - POSTGRES_PASSWORD=${SQL_PASSWORD:-default_ps}
        - POSTGRES_DB=${SQL_DATABASE:-default_db}
    volumes:
      - /home/tdutel/data/Pong_back:${PSQL_DATA_REPO}
    env_file:
      - .env
    ports:
      - "5430:5432"
    networks:
      - Pong_back_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $USER"]
      start_period: 5s
      retries: 10
      interval: 15s
      timeout: 10s
    restart: on-failure

networks:
  backend:
    external: true
  Pong_back_db:
    name: Pong_back_db
    driver: bridge
