services:
  web:
    build:
      context: ./django
      args:
        - VOLUME=${DJANGO_WORKDIR_AI:-/home/AI}
        - LAUNCH=${DJANGO_LAUNCH_REPO:-/run/launch}
    container_name: django_ai
    ports:
      - "8005:8000"
    env_file:
      - .env
