# Generated by Django 4.2.17 on 2025-01-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcul', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='pongDB',
        ),
    ]
