services:
  front:
    build:
      context: ./Bootstrap
      args:
        - VOLUME=${BOOT_WORKDIR:-/home/front}
        - PORT=${PORT_FRONT:-3000}
    container_name: Frontend
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ../../Front:${BOOT_WORKDIR:-/home/front}
    env_file:
      - ./.env
    networks:
      - frontend
    restart: always

networks:
  frontend:
    external: true
    driver: bridge