services:
  db:
    image: esdes/postgresql:alive_latest
    ports:
      - "5432:5432"
    # volumes:
    #   - microservice:/var/lib/postgresql/data     # c'est peut etre la caus ede mes problèmes car ca efface peut etre tous ce qui est fait dans ce conteneur ? (comme l'erreure juste avant)
    environment:
      POSTGRES_DB: test_django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123soleil

  web:
    build:
      context: ./test_django
      dockerfile: Dockerfile
    command: /run/app/launch.sh
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DJANGO_SUPERUSER_USERNAME: "moi"
      DJANGO_SUPERUSER_PASSWORD: "moi123moi"
      DJANGO_SUPERUSER_EMAIL: "eslmaber@student.42lyon.fr"
      DATABASE_URL: postgres://django_user:123soleil@db:5432/test_django
      USER: "postgres"
      DATA_DIR: "/var/lib/postgresql/data"
    volumes:
      - microservice:/var/lib/postgresql/data

volumes:
  microservice:
    driver: local
    name: micro
    driver_opts:
      type: none
      o: bind
      device: /home/eslamber/data/micro

networks:
  test:
    name: test_micro
    driver: bridge