services:
  web:
    build:
      context: ./django
      args:
        - VOLUME:${DJANGO_WORKDIR}
        - LAUNCH:${DJANGO_LAUNCH_REPO}
    container_name: django_app
    #    command: gunicorn configFiles.wsgi:application --bind 0.0.0.0:8000 --reload
    command: python manage.py runserver 0.0.0.0:8000          # <-- Add this line for hot reload
    ports:
      - "8000:8000"
    volumes:
      - ../test_django/app:${DJANGO_WORKDIR} # TODO : mettre l'endroit ou il est sensé repiocher le code dans le conteneur
    environment:
      - POSTGRES_USER=${SQL_USER:-default_us}
      - POSTGRES_PASSWORD=${SQL_PASSWORD:-default_ps}
      - POSTGRES_DB=${SQL_DATABASE:-default_db}
    #   - DATABASE_URL=postgres://$SQL_USER:SQL_PASSWORD@SQL_HOST:SQL_PORT/SQL_DATABASE
    env_file:
      - ./.env
    depends_on:
      # - db
      db:
        condition: "service_healthy"
    restart: always
    # healthcheck:
    #   test: ["CMD", "curl", "-k", "http://localhost:8000/test"] # Je pense pas utils pour l'instant

  db:
    container_name: postgreSQL
    build:
      context: ./postgresql
      args:
        - POSTGRES_USER=${SQL_USER:-default_us}
        - POSTGRES_PASSWORD=${SQL_PASSWORD:-default_ps}
        - POSTGRES_DB=${SQL_DATABASE:-default_db}
        # - USER=${PSQL_USER:-postgres}
        # - PASS=${PSQL_PASS:-moi123moi}
        # - HOST=${PSQL_HOST:-localhost}
        # - DATA=${PSQL_DATA_REPO:-/var/lib/postgresql/data/}
    volumes:
      - /home/eslamber/data:${PSQL_DATA_REPO}
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $USER"]
      start_period: 5s
      retries: 10
      interval: 15s
      timeout: 10s
    restart: on-failure
