# Generated by Django 4.2.16 on 2024-09-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personne',
            name='age',
        ),
        migrations.RemoveField(
            model_name='personne',
            name='email',
        ),
        migrations.AddField(
            model_name='personne',
            name='mdp',
            field=models.CharField(default='defPass', max_length=100),
        ),
        migrations.AlterField(
            model_name='personne',
            name='nom',
            field=models.CharField(default='defName', max_length=100),
        ),
    ]
