services:
  api_web:
    build:
      context: ./django
      args:
        - VOLUME=${DJANGO_WORKDIR:-/home/API}
        - LAUNCH=${DJANGO_LAUNCH_REPO:-/run/launch}
    container_name: django-API
    command: python manage.py runserver 0.0.0.0:8000 
    ports:
      - "8000:8000"
    volumes:
      - ../djpr_API:${DJANGO_WORKDIR:-/home/API}
    environment:
      - POSTGRES_USER=${PSQL_USER:-default_us}
      - POSTGRES_PASSWORD=${PSQL_PASS:-default_ps}
      - POSTGRES_DB=${SQL_DATABASE:-default_db}
    env_file:
      - .env
    depends_on:
      api_psql:
        condition: "service_healthy"
    networks:
      - backend
      - frontend
      - api_db
    restart: always

  api_psql:
    container_name: postgreSQL-API
    build:
      context: ./postgresql
      args:
        - POSTGRES_USER=${PSQL_USER:-default_us}
        - POSTGRES_PASSWORD=${PSQL_PASS:-default_ps}
        - POSTGRES_DB=${SQL_DATABASE:-default_db}
    volumes:
      - /home/eslamber/data/API:${PSQL_DATA_REPO}
      - ./postgresql/tools:/docker-entrypoint-initdb.d
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - api_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $USER"]
      start_period: 5s
      retries: 10
      interval: 15s
      timeout: 10s
    restart: on-failure

networks:
  backend:
    name: backend
    driver: bridge

  frontend:
    name: frontend
    driver: bridge
  
  api_db:
    name: api_db
    driver: bridge