# Generated by Django 4.2.17 on 2024-12-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djap_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fulluser',
            name='language',
            field=models.CharField(default='fr', max_length=2),
        ),
        migrations.AddField(
            model_name='fulluser',
            name='secu',
            field=models.BooleanField(default=True),
        ),
    ]
