# Generated by Django 4.2.17 on 2025-01-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djap_login', '0003_remove_fulluser_pseudo_fulluser_realname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fulluser',
            name='phone_nb',
        ),
    ]
