# Generated by Django 4.2.17 on 2024-12-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djap_register', '0005_alter_userprofile_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='FtTokenModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=250)),
            ],
        ),
    ]
