# Generated by Django 4.2.17 on 2024-12-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='player_list',
            field=models.JSONField(default=list),
        ),
    ]
