# Generated by Django 4.2.17 on 2025-01-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcul', '0002_tournament_player_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rounds',
            field=models.IntegerField(default=0),
        ),
    ]
