# Generated by Django 4.2.17 on 2024-12-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcul', '0002_tournament_player_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='tournament',
        ),
        migrations.AddField(
            model_name='player',
            name='game_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='winscore',
            field=models.IntegerField(default=0),
        ),
    ]
