# Generated by Django 4.2.17 on 2024-12-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcul', '0003_remove_player_tournament_player_game_played_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=100)),
                ('player2', models.CharField(max_length=100)),
                ('winner', models.CharField(max_length=100)),
            ],
        ),
    ]
