# Generated by Django 4.2.17 on 2025-01-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcul', '0003_player_score_tournament_rounds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='tournament',
        ),
        migrations.AddField(
            model_name='player',
            name='match_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(related_name='players', to='calcul.player'),
        ),
    ]
