# Generated by Django 4.2.17 on 2025-01-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcul', '0005_rename_rounds_tournament_curr_round_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='curr_round',
            field=models.IntegerField(default=1),
        ),
    ]
