# Generated by Django 4.2.17 on 2025-01-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcul', '0007_pair_tournament_pairs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
