# Generated by Django 4.2.18 on 2025-01-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcul', '0011_alter_tournament_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, unique=True),
        ),
    ]
