# Generated by Django 4.2.18 on 2025-01-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcul', '0012_alter_tournament_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='from_Tournament',
            field=models.CharField(default='', max_length=100),
        ),
    ]
