# Generated by Django 4.2.18 on 2025-01-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcul', '0013_player_from_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='htmlbackup',
            field=models.JSONField(default=dict),
        ),
    ]
