# Generated by Django 4.2.18 on 2025-01-17 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcul', '0014_tournament_htmlbackup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='htmlbackup',
        ),
    ]
