# Generated by Django 4.2.16 on 2025-01-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcul', '0015_remove_tournament_htmlbackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='from_uuid',
            field=models.CharField(default=None, max_length=40, unique=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='uuid',
            field=models.CharField(default=None, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='username',
            field=models.CharField(default=None, max_length=150, unique=True),
        ),
    ]
