# Generated by Django 4.2.16 on 2025-01-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcul', '0016_player_from_uuid_tournament_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='from_uuid',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
