services:
  front:
    build:
      context: ./Nginx
      args:
        - VOLUME=${NGINX_WORKDIR:-/home/front}
        - PORT=${PORT_FRONT:-443}
    container_name: Frontend
    ports:
      - "3000:443"
    volumes:
      - ../S_Front:${NGINX_WORKDIR:-/home/front}
    env_file:
      - ./.env
    networks:
      - frontend
    restart: always

networks:
  frontend:
    name: frontend
    driver: bridge
